import { dirname } from "path";
import { fileURLToPath } from "url";
import { FlatCompat } from "@eslint/eslintrc";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const compat = new FlatCompat({
  baseDirectory: __dirname,
});

/**
 * ESLint flat config — Next.js 15 + TypeScript + Prettier
 *
 * next/core-web-vitals: React, JSX, hooks, accessibility, Next.js rules
 * next/typescript:      TypeScript-specific rules (wraps @typescript-eslint/recommended)
 * prettier:             Disables formatting rules that conflict with Prettier
 */
const config = [
  ...compat.extends("next/core-web-vitals", "next/typescript", "prettier"),

  {
    rules: {
      // Disallow `any` — forces proper typing throughout the codebase
      "@typescript-eslint/no-explicit-any": "error",

      // Disallow unused variables (allow underscore-prefixed intentional ignores)
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
      ],

      // React 19 — JSX transform active, no need to import React in scope
      "react/react-in-jsx-scope": "off",

      // Enforce `import type` for type-only imports (keeps bundles clean)
      "@typescript-eslint/consistent-type-imports": ["warn", { prefer: "type-imports" }],

      // Warn on missing return types for exported functions
      "@typescript-eslint/explicit-module-boundary-types": "warn",
    },
  },

  {
    ignores: [
      ".next/**",
      "node_modules/**",
      "next-env.d.ts", // auto-generated by Next.js — do not lint
      "components/ui/**", // shadcn/ui generated — third-party code, not linted
    ],
  },
];

export default config;
